# Generated by Django 4.1.5 on 2023-01-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options_review_created_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-voted_ratio', '-voted_total', 'title']},
        ),
    ]
